### ISSUE TITLE
Connection error when reopening GOG Galaxy

### ISSUE THREAD

**Issue by Balnian** [BellezaEmporium/galaxy-integration-ead#13]
**Describe the bug**
Everytime I open GOG galaxy I get prompted to reauthenticate with EA login.
Once I login the plugin fails (lost connection)

I'm running the latest version of the plugin (0.43)

**To Reproduce**
1. Log in 
2. Enter valid EA credentials when prompted
3. See that plugin has lost connection

**Expected behavior**
No subsequent login should be needed after initial setup of plugin and plugin shouldn't lose connection

**Attached logs**
Note, I have added some extra logging info to some section trying to understand why my games where not updating (ex.: timestamp for cache refresh)
```
2024-11-21 03:02:38,321 - galaxy.api.jsonrpc - INFO - Handling request: id=4, method=init_authentication, params={'stored_credentials': '****'}
2024-11-21 03:02:38,321 - plugin - INFO - Starting authentication process
2024-11-21 03:02:38,321 - galaxy.api.jsonrpc - INFO - Sending notification: method=store_credentials, params={'cookies': '****'}
2024-11-21 03:02:38,792 - plugin - DEBUG - Local games cache is fresh enough (1732125758.1341584)
2024-11-21 03:02:39,122 - plugin - INFO - HTTP client authenticated
2024-11-21 03:02:39,318 - http_client - ERROR - Error in _get_access_token: 
Traceback (most recent call last):
  File "C:\Users\super\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_v0.43\http_client.py", line 145, in _get_access_token
    raise AccessDenied("Unexpected response when getting access token")
galaxy.api.errors.AccessDenied
2024-11-21 03:02:39,319 - plugin - ERROR - Failed to authenticate: AccessDenied()
Traceback (most recent call last):
  File "C:\Users\super\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_v0.43\plugin.py", line 198, in _do_authenticate
    self._access_token, self._refresh_token = await self._http_client._get_access_token()
  File "C:\Users\super\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_v0.43\http_client.py", line 145, in _get_access_token
    raise AccessDenied("Unexpected response when getting access token")
galaxy.api.errors.AccessDenied
2024-11-21 03:02:39,319 - galaxy.api.jsonrpc - ERROR - Sending data: {"jsonrpc": "2.0", "id": "4", "error": {"code": 100, "message": "Invalid credentials", "data": {"internal_type": "InvalidCredentials"}}}
```

**Comment by BellezaEmporium** [comment]
Issue is known and a fix is currently being tested in 0.44 https://github.com/BellezaEmporium/galaxy-integration-ead/tree/junoapi-test

**Comment by BellezaEmporium** [comment]
Please try 0.44 https://github.com/BellezaEmporium/galaxy-integration-ead/releases/tag/v44

**Comment by BellezaEmporium** [comment]
Considering the age of the issue and the fact that most authentication errors have been fixed by now, moving this as completed.
