### ISSUE TITLE
EA APP Games wont show on GOG Galaxy (v.043)

### ISSUE THREAD

**Issue by alfredox123** [BellezaEmporium/galaxy-integration-ead#14]
EA APP games doesnt show on GOG Galaxy, it says importing after log in with ea account on gog galaxy, but after waiting it doesnt import anything.

[plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/user-attachments/files/18223414/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

**Comment by BellezaEmporium** [comment]
Errors seem to pinpoint "wmic" as the culprit.

```
2024-12-21 15:07:25,616 - galaxy.api.jsonrpc - ERROR - Unexpected exception raised in plugin handler
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0\galaxy\api\jsonrpc.py", line 271, in handle
    result = await callback(*bound_args.args, **bound_args.kwargs)
  File "C:\Users\*****\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0\galaxy\api\plugin.py", line 252, in method
    result = await handler_(*args, **kwargs)
  File "C:\Users\*****\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0\galaxy\api\plugin.py", line 264, in wrapper
    return await self._external_task_manager.create_task(handler(*args, **kwargs), name, False)
  File "C:\Users\*****\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0\galaxy\task_manager.py", line 21, in task_wrapper
    result = await coro
  File "C:\Users\*****\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0\plugin.py", line 197, in authenticate
    return await self._begin_auth_flow()
  File "C:\Users\*****\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0\plugin.py", line 200, in _begin_auth_flow
    pc_sign_definition = PCSign(sv=PCSignVersion.V2)
  File "<string>", line 5, in __init__
  File "C:\Users\*****\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0\pcsign_hash.py", line 40, in __post_init__
    self.gather_hardware_info()
  File "C:\Users\*****\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0\pcsign_hash.py", line 46, in gather_hardware_info
    self.gather_windows_info()
  File "C:\Users\*****\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0\pcsign_hash.py", line 56, in gather_windows_info
    self.bsn = self.run_wmic("bios get serialnumber").strip()
  File "C:\Users\*****\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0\pcsign_hash.py", line 53, in run_wmic
    return subprocess.check_output(f"wmic {command}", shell=True).decode().split('\n')[1]
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\subprocess.py", line 395, in check_output
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\subprocess.py", line 487, in run
subprocess.CalledProcessError: Command 'wmic bios get serialnumber' returned non-zero exit status 1.
```

This is actually linked to the pc_sign.py program, creating the PCSign header when logging in to the EA servers. The error seems to indicate it couldn't get a positive answer on the PC's serial number.

![image](https://github.com/user-attachments/assets/cdb219f0-60e6-42e2-8e56-2b4d13536b19)

**Comment by Nutzzz** [comment]
I don't know if this is the problem, but in my travels I ran across a PC where the default wmic aliases had been deleted somehow, but I could still use something like "wmic path win32_bios \<command\>" instead of "wmic bios \<command\>".

Also, FWIW, wmic has been deprecated in favor of the PowerShell WMI module. In the latest Server 2025 preview, wmic is now an optional feature. I've read that the latest Win11 preview will be doing the same.

**Comment by BellezaEmporium** [comment]
> I don't know if this is the problem, but in my travels I ran across a PC where the default wmic aliases had been deleted somehow, but I could still use something like "wmic path win32_bios <command>" instead of "wmic bios <command>".
> 
> Also, FWIW, wmic has been deprecated in favor of the PowerShell WMI module. In the latest Server 2025 preview, wmic is now an optional feature. I've read that the latest Win11 preview will be doing the same.

Sounds like it could have been the case somewhere. Using WMI would mean to install the "WMI" extension (along with PyWin32) as an additional package to the rest. IIRC we had issues using that out.

**Comment by BellezaEmporium** [comment]
I've managed to use Powershell without the need of WMI, and it seems to work on my watch. I use -Get-CimInstance.

**Comment by alfredox123** [comment]
it logs in now, but still doesnt show the games on gog galaxy

**Comment by BellezaEmporium** [comment]
Could you attach your new log file in this discussion ? That can permit me to pinpoint the issue.

**Comment by alfredox123** [comment]
Sorry, here it is.
*snip, for safety*

**Comment by BellezaEmporium** [comment]
Now that's interesting. The new log doesn't show any error linked to the plugin. Sounds like Galaxy's being lazy. The only errors I see are registry related, and that's for local games installation lookup (they would still show anyway, just not switched as "installed").

On my POV, It actually sees the games, if you look at the lines starting at 2024-12-29 22:01:17,958

You may try and restart Galaxy, and check if the "Origin" tab loads up on the panel, in your left side.

**Comment by alfredox123** [comment]
restarting doesnt do anything, it doesnt import ea app games. Only steam, ubisoft connect, epic and xbox app

**Comment by BellezaEmporium** [comment]
That's odd, really... Your log didn't indicate an issue that could have been linked to the plugin (with the new patch/commit), which is why that surprises me. I'll keep looking, just in case, but right now I do not have any idea of where that could block.

**Comment by BellezaEmporium** [comment]
Please try https://github.com/BellezaEmporium/galaxy-integration-ead/releases/tag/v44

**Comment by alfredox123** [comment]
can you explain me the process to install it? i forgot sorry

**Comment by BellezaEmporium** [comment]
Just extract the contents of the plugin to %LOCALAPPDATA%/GOG.com/Galaxy/plugins/installed/origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0

**Comment by BellezaEmporium** [comment]
Release 0.44.4 has improved game finding and also refined pc_sign methods, so maybe it can help with your issue.

**Comment by BellezaEmporium** [comment]
Considering this as complete, closing due to OP not answering anymore.
